### ISSUE TITLE
Unable to locate a class or view for component [navbar]

### ISSUE THREAD

**Issue by T-Tron** [AbdullahSaad5/playtaeu#1]
Hi, i have a error when i put your site 👍 

Unable to locate a class or view for component [navbar]. (View: /var/www/vhosts/switchcompagnie.eu/moba-chocolate.switchcompagnie.eu/resources/views/layouts/base.blade.php)

How i can fix that ?

**Comment by AbdullahSaad5** [comment]
I've just checked and it's working fine on my end. Moreover, it was a semester project with me as a sole developer. This project will not be supported anymore. Sorry.
